// -------------------------------------------------------------
// 
// File Name: D:\Kursach\hdlsrc\CIC_fixp1\CIC_tc.v
// Created: 2020-11-16 22:11:48
// 
// Generated by MATLAB 9.3 and HDL Coder 3.11
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: CIC_tc
// Source Path: CIC_tc
// Hierarchy Level: 1
// 
// Master clock enable input: clk_enable
// 
// enb         : identical to clk_enable
// enb_1_2_0   : 2x slower than clk with last phase
// enb_1_2_1   : 2x slower than clk with phase 1
// enb_1_4_0   : 4x slower than clk with last phase
// enb_1_4_1   : 4x slower than clk with phase 1
// enb_1_20_1  : 20x slower than clk with phase 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module CIC_tc
          (clk,
           reset,
           clk_enable,
           enb,
           enb_1_2_0,
           enb_1_2_1,
           enb_1_4_0,
           enb_1_4_1,
           enb_1_20_1);


  input   clk;
  input   reset;
  input   clk_enable;
  output  enb;
  output  enb_1_2_0;
  output  enb_1_2_1;
  output  enb_1_4_0;
  output  enb_1_4_1;
  output  enb_1_20_1;

  reg  count2;
  reg  phase_0;
  wire phase_0_tmp;
  reg  phase_1;
  wire phase_1_tmp;
  reg [1:0] count4;  // ufix2
  reg  phase_0_1;
  wire phase_0_tmp_1;
  reg  phase_1_1;
  wire phase_1_tmp_1;
  reg [4:0] count20;  // ufix5
  wire phase_all;
  reg  phase_1_2;
  wire phase_1_tmp_2;


  always @ (posedge clk or posedge reset)
    begin: Counter2
      if (reset == 1'b1) begin
        count2 <= 1'b1;
      end
      else begin
        if (clk_enable == 1'b1) begin
            count2 <= ~ count2;
        end
      end
    end // Counter2

  always @ (posedge clk or posedge reset)
    begin: temp_process1
      if (reset == 1'b1) begin
        phase_0 <= 1'b0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          phase_0 <= phase_0_tmp;
        end
      end
    end // temp_process1

  assign  phase_0_tmp = (count2 == 1'b1 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  always @ (posedge clk or posedge reset)
    begin: temp_process2
      if (reset == 1'b1) begin
        phase_1 <= 1'b1;
      end
      else begin
        if (clk_enable == 1'b1) begin
          phase_1 <= phase_1_tmp;
        end
      end
    end // temp_process2

  assign  phase_1_tmp = (count2 == 1'b0 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  always @ (posedge clk or posedge reset)
    begin: Counter4
      if (reset == 1'b1) begin
        count4 <= 2'b01;
      end
      else begin
        if (clk_enable == 1'b1) begin
          if (count4 >= 2'b11) begin
            count4 <= 2'b00;
          end
          else begin
            count4 <= count4 + 2'b01;
          end
        end
      end
    end // Counter4

  always @ (posedge clk or posedge reset)
    begin: temp_process3
      if (reset == 1'b1) begin
        phase_0_1 <= 1'b0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          phase_0_1 <= phase_0_tmp_1;
        end
      end
    end // temp_process3

  assign  phase_0_tmp_1 = (count4 == 2'b11 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  always @ (posedge clk or posedge reset)
    begin: temp_process4
      if (reset == 1'b1) begin
        phase_1_1 <= 1'b1;
      end
      else begin
        if (clk_enable == 1'b1) begin
          phase_1_1 <= phase_1_tmp_1;
        end
      end
    end // temp_process4

  assign  phase_1_tmp_1 = (count4 == 2'b00 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  always @ (posedge clk or posedge reset)
    begin: Counter20
      if (reset == 1'b1) begin
        count20 <= 5'b00001;
      end
      else begin
        if (clk_enable == 1'b1) begin
          if (count20 >= 5'b10011) begin
            count20 <= 5'b00000;
          end
          else begin
            count20 <= count20 + 5'b00001;
          end
        end
      end
    end // Counter20

  assign phase_all = clk_enable ? 1'b1 : 1'b0;

  always @ (posedge clk or posedge reset)
    begin: temp_process5
      if (reset == 1'b1) begin
        phase_1_2 <= 1'b1;
      end
      else begin
        if (clk_enable == 1'b1) begin
          phase_1_2 <= phase_1_tmp_2;
        end
      end
    end // temp_process5

  assign  phase_1_tmp_2 = (count20 == 5'b00000 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  assign enb =  phase_all & clk_enable;

  assign enb_1_2_0 =  phase_0 & clk_enable;

  assign enb_1_2_1 =  phase_1 & clk_enable;

  assign enb_1_4_0 =  phase_0_1 & clk_enable;

  assign enb_1_4_1 =  phase_1_1 & clk_enable;

  assign enb_1_20_1 =  phase_1_2 & clk_enable;


endmodule  // CIC_tc
